#! /bin/sh
# config enviroment 
echo "config enviroment..."
export LD_LIBRARY_PATH=/tmp/:$LD_LIBRARY_PATH
echo "LD_LIBRARY_PATH=" $LD_LIBRARY_PATH

# ldd to list libraries dependenciss
ldd /tmp/test

# run
/tmp/test

